export const ORIGINAL_REPOSITORY_URL =
  'https://github.com/angelabenavente/github-profile-sh';

export const SVG_LICENSE_URL = 'https://creativecommons.org/licenses/by/4.0/';

export const generatedSvgAttributionComment = `<!-- Generated by github-profile.sh. Original: ${ORIGINAL_REPOSITORY_URL}. SVG licensed under CC BY 4.0: ${SVG_LICENSE_URL} -->`;
